// These tests assume access to a mySql installation
var fs               = require("fs");
var should           = require("should");
var Sequelize        = require('Sequelize');
var uuid             = require('node-uuid');
var Promise          = require("bluebird");

var utils            = require('./../utils.js');
var dbUtils          = require('./../dbUtils.js');
var SequelizeManager = require('./../SequelizeManager');

var _ = Sequelize.Utils._;
var log = utils.log;
// log.enabled = false;

var dbConfig = {
  host: "localhost",
  user: "root",
  password: "password",
  dbName: 'test1'
}

var _nwDbInitialized = false;
var _nwSm;

describe("sequelize", function() {
  this.enableTimeouts(false);

  before(function(done) {
    // this.enableTimeouts(false);
    syncNw().then(function(sm) {
      _nwSm = sm;
    }).then(done, done);

   });

  it("should create a simple schema", function(done) {
    var sm = new SequelizeManager(dbConfig);
    createSimpleSchema(sm.sequelize);
    // this will not work but the line after will;
    // sm.sync(true).then(done, done);
    // sm.sync(true).then(done.bind(null, null), done);
    // or
    sm.sync(true).then(noop).then(done, done);

  });

  function noop() {};


  it("should convert breeze metadata", function() {
    should.exist(_nwSm);
    var CustomerModel = _nwSm.models.Customer;
    should.exist(CustomerModel);
  });

  it("should save simple with build", function(done) {
    var Customer = _nwSm.models.Customer;
    var dtos = createCustDTOs();
    var cust1 = Customer.build( dtos[0]);
    cust1.save().then(function(c1) {
      c1.companyName.should.equal("Test 1");
    }).then(function() {
      var cust2 = Customer.build( dtos[1]);
      return cust2.save();
    }).then(function(c2) {
      c2.companyName.should.equal("Test 2");
    }).then(done, done);
  });

  it("should insert with create", function(done) {
    var Customer = _nwSm.models.Customer;
    var dtos = createCustDTOs();
    Customer.create( dtos[0] ).then(function(c1) {
      c1.companyName.should.equal("Test 1");
      return Customer.create( dtos[1]);
    }).then(function(c2) {
      c2.companyName.should.equal("Test 2");
    }).then(done, done);
  });

  it("should insert with bulk create", function(done) {
    var Customer = _nwSm.models.Customer;
    var dtos = createCustDTOs();
    Customer.bulkCreate( dtos).then(function(r) {
      r.should.have.length(dtos.length);
    }).then(done, done);
  });

  it("should insert with create and an autogenerated key", function(done) {
    var Employee = _nwSm.models.Employee;
    var dtos = createEmpDTOs();
    var emp0, emp1;
    Employee.create(dtos[0]).then(function(emp) {
      emp0 = emp;
      // this 1st one will always be 0
      emp0.employeeID.should.not.equal(0);
      return Employee.create(dtos[1]);
    }).then(function(emp) {
      emp1 = emp;
      emp1.employeeID.should.not.equal(emp0.employeeID);
    }).then(done, done);

  });

  it("should insert with create using promises 'all' and an autogenerated key", function(done) {
    var Employee = _nwSm.models.Employee;
    var dtos = createEmpDTOs();
    Promise.all(dtos.map(function(dto) {
      return Employee.create(dto);
    })).then(function(emps) {
      emps.should.have.length(dtos.length);
    }).then(done, done);
  });

  it("should insert with bulkCreate and an autogenerated key", function(done) {
    var Employee = _nwSm.models.Employee;
    var dtos = createEmpDTOs();

    // Will not be able to use this feature because
    // Sequelize does not provide a way to retrieve the key when using bulkCreate
    Employee.bulkCreate( dtos).then(function(r) {
      r.should.have.length(dtos.length);
    }).then(done, done);
  });
});

function createCustDTOs() {
  return [
    { customerID: uuid.v1(), companyName: "Test 1", City: "Los Angeles" },
    { customerID: uuid.v1(), companyName: "Test 2", City: "Oakland" }
  ];
}

function createEmpDTOs() {
  return [
    {   lastName: "Smith", firstName: "Don", birthDate: new Date(2001, 0, 1)},
    {   lastName: "Doe",   firstName: "John", birthDate: new Date(2001, 1, 1)},
    {   lastName: "Smith", firstName: "Mary", birthDate: new Date(2001, 2, 1)}
  ]
}

function createOrderDTOs() {
  return {

  };
}


function initializeNw() {
  nwConfig = _.clone(dbConfig);
  nwConfig.dbName = "NorthwindIB";
  var sm = new SequelizeManager(nwConfig);
  var breezeMetadata = fs.readFileSync('./test/sampleMetadata.json', { encoding: 'utf8' });
  sm.importMetadata(breezeMetadata);
  return sm;
}

// returns promise(sm)
function syncNw() {
  var sm = initializeNw();
  return sm.sync(true).then(function() {
    return sm;
  }).error(function(err) {
    log("syncNw failed" + err);
    throw(err);
  });

}


function createSimpleSchema(sequelize) {
  var Customer = sequelize.define("customer", {
    customerId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
    companyName: { type: Sequelize.STRING, allowNull: false },
    city: { type: Sequelize.STRING }
  });
  var Order = sequelize.define("order", {
    orderId: { type: Sequelize.INTEGER, primaryKey: true, autoIncrement: true },
    shippingCost: {type: Sequelize.DECIMAL(11,2), allowNull: false },
    orderDate: { type: Sequelize.DATE  },
    shipDate: { type: Sequelize.DATE }
  });
  Order.belongsTo(Customer, { as: "myCustomer", foreignKey: "custId"})
  Customer.hasMany(Order, { as: "myOrders", foreignKey: "custId" } );

}

